% Exercise 9. T-61.5110 Modelling of Biological Networks, Aalto University.
% Suleiman Ali Khan 13.11.11

% Question 1.a
Sequences = { 'AGTAGCCA' 'CGTTCCTACA' 'GTTGGTACC' 'GTTGCCA' 'TGTCGCCATG' 'CGTTGTCAT' 'AGTTACCA' 'GTTAGCACA' 'GTTTTTATG' 'GGTTGGTA' }
Aligned_Sequences = multialign(Sequences)

% Question 1.b
multialignviewer(Aligned_Sequences)

% Question 1.c
Consensus_Sequence = seqconsensus(Aligned_Sequences(:,2:8))
seqlogo(Aligned_Sequences(:,2:8))

% Question 1.d
%   position specific weight matrix 
%   (PSWM). Matrix consists of positive values such that each
%   column sums up to one. M(i,j) defines the frequency of base
%   pair i at position j in the site/motif M.
%   Replace F here with the one from Question 1.d.
F = [0 0 0 0 0 0 0; 0.9 0.2 0.2 0.2 0.2 0.2 0.2; 0.1 0.8 0.8 0.8 0.1 0.1 0.1; 0 0 0 0 0.7 0.7 0.7 ] 

% Question 2
M22326 = 'CGCGGGCGTCCCCGACTCCCGCGCGCGCTCAGGCTCCCAGTTGGGAACCAAGGAGGGGGAGGATGGGGGGGGGGGGTGTGCGCCGACCCGGAAACGCCATATAAGGAGCAGGAAGGATCCCCCGCCGGAACAGACCTTATTTGGGCAGCGCCTTATATGGAGTGGCCCAATATGGCCCTGCCGCTTCCGGCTCTGGGAGGAGGGGCGAGCGGGGGTTGGGGCGGGGGCAAGCTGGGAACTCCAGGCGCCTGGCCCGGGAGGCCACTGCTGCTGTTCCAATACTAGGCTTTCCAGGAGCCTGAGCGCTCGCGATGCCGGAGCGGGTCGCAGGGTGGAGGTGCCCACCACTCTTGGATGGGAGGGCTTCACGTCACTCCGGGTCCTCCCGGCCGGTCCTTCCATATTAGGGCTTCCTGCTTCCCATATATGGCCATGTACGTCACGGCGGAGGCGGGCCCGTGCTGTTCCAGACCCTTGAAATAGAGGCCGATTCGGGGAGTC'
X04724 = 'ACTGGGTCCCCACTACCTTTATAGACCAAAGCACCTCCTCTCTGCCCCCTGGACTTTGCTGTTTGACCCATTAAGGGCTCCAGGTGGGGTAGGTCAGCAGATGGCCAGAGGGGCTGAAGCTGCAGTTTCCAAACACTTCCCTGGTGCTAGGTCTGCAGAAAGCGCTCATTGGACGTCAACACCTCTACTTAGTCCTAGGGTAATTAGAGTCTTAACAAGGGGCCCTGATGGCCTGATGAACCAGTTCACAGCAGGGGACATTGTTCCAGAGTGGGTGATGCTTTCTTTGTCCTTGGCTGAGCATTTTTCCACATCATTCCCCAGGAAGTTGCAGTTGGGGACCTAGTATCTTTGTCCCTTGGACTGTTTCACAGTTCCAATTGATAGCTGGGTTCTTAACTCAGCCGAGTCCCCAGCTCTCTCTCAGAGGTAGAAGGAAAGCAGAATTCAGGCAGCAAGGCACTTAATGGTCCCTCCTCCTCTATCTCTCTTTCCATATC'

M22326_n = basepairs2num(M22326);
M22326_ml = PSWM_MotifLocator(M22326_n,F,0.25*ones(1,4),0,[],[]);

X04724_n = basepairs2num(X04724);
X04724_ml = PSWM_MotifLocator(X04724_n,F,0.25*ones(1,4),0,[],[]);

max(M22326_ml) %which sequence has the most likely match
max(X04724_ml) 

find(M22326_ml == max(M22326_ml)) %which is the most likely position
find(X04724_ml == max(X04724_ml)) %which is the most likely position


